version: '3'

services:

  postgres:

    image: postgres:13

    container_name: airflow-postgres

    environment:

      POSTGRES_USER: airflow

      POSTGRES_PASSWORD: airflow

      POSTGRES_DB: airflow

    ports:

      - "5433:5432"
     

    volumes:

      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:

    build: .
    user: "0:0"

    container_name: airflow-webserver


    depends_on:

      - postgres

    environment:
      

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"

    volumes:

      - ./dags:/opt/airflow/dags

      - ./logs:/opt/airflow/logs

      - ./plugins:/opt/airflow/plugins

      - ../src:/opt/airflow/src

      - ./udif-input:/opt/airflow/udif-input
      - ./udif-output:/opt/airflow/udif-output
      




    ports:

      - "8080:8080"

    command: webserver
 

  airflow-scheduler:

    build: .
    user: "0:0"
    container_name: airflow-scheduler

    depends_on:

      - postgres

    environment:

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"

    volumes:

      - ./dags:/opt/airflow/dags

      - ./logs:/opt/airflow/logs

      - ./plugins:/opt/airflow/plugins

      - ../src:/opt/airflow/src
      - ./udif-input:/opt/airflow/udif-input
      - ./udif-output:/opt/airflow/udif-output

    command: scheduler
 

volumes:

  postgres-db-volume: